from dataclasses import dataclass, field
from typing import Callable, Protocol

from app.pipeline.stt import Cue


class TranslationError(Exception):
    pass


def _noop_progress(frac: float) -> None: ...
def _noop_cancel() -> None: ...


@dataclass
class SceneInfo:
    """Per-scene metadata passed to the translator. The `description` is the
    1-2 sentence scene bible entry generated by the configured Vision LLM in
    scene/cinematic modes."""
    index: int
    start: float
    end: float
    description: str


@dataclass
class TranslationContext:
    """Optional extra context for higher-tier modes. Providers ignore fields
    they don't support — DeepL and NLLB are text-only and silently drop these.

    - `scenes`: full scene bible for the media (sent in the cached system prefix
      so it doesn't repeat per cue batch).
    - `cue_to_scene`: cue.id → scene.index, so the translator can annotate each
      cue with the right scene description without resending the full bible.
    - `cue_frames`: cue.id → JPEG bytes (cinematic mode only). When set, the
      translator attaches each frame as an image block alongside its cue.
    """
    scenes: list[SceneInfo] = field(default_factory=list)
    cue_to_scene: dict[int, int] = field(default_factory=dict)
    cue_frames: dict[int, bytes] = field(default_factory=dict)


class TranslationProvider(Protocol):
    def translate(
        self,
        cues: list[Cue],
        source_lang: str,
        target_lang: str,
        context: TranslationContext | None = None,
        *,
        progress: Callable[[float], None] = _noop_progress,
        check_cancel: Callable[[], None] = _noop_cancel,
    ) -> list[Cue]:
        """Translate cues, optionally using extra `context` for higher-tier modes.
        Timing (start/end) and ids must be preserved. Length must match input.
        Providers without multimodal capability ignore `context` and translate
        text only. `progress` is called with fractional completion in [0,1] as
        batches finish; `check_cancel` is called between batches and raises
        JobCanceled if the user has clicked cancel.
        """
        ...
